/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.management;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class CustomerCheckin extends javax.swing.JFrame {
    
        Connection con=null;
        Statement st=null;
        PreparedStatement pst=null;
        ResultSet rs=null;

    /**
     * Creates new form CustomerCheckin
     */
    public CustomerCheckin() {
        initComponents();
        scaleImage();
        // Other initialization code...
        SimpleDateFormat obj=new SimpleDateFormat("yyyy/MM/dd");
        Date date=new Date();
        txtdate.setText(obj.format(date));
        
            try { 
                Class.forName("com.mysql.cj.jdbc.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotels","root","");
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(ManageRoom.class.getName()).log(Level.SEVERE, null, ex);
            }
        shyam();    
    }
    
    public void shyam(){
            try {
                pst=con.prepareStatement("Select roomnumber from room where bed=? and roomtype=? and status=?");
                pst.setString(1,combobed.getItemAt(combobed.getSelectedIndex()));
                pst.setString(2,comboroomtype.getItemAt(comboroomtype.getSelectedIndex()));
                pst.setString(3, "NOT-BOOKED");
                rs=pst.executeQuery();
                comboroomnumber.removeAllItems();
                while(rs.next()){
                    comboroomnumber.addItem(rs.getString("roomnumber"));
                }
                pst=con.prepareStatement("select price from room where roomnumber=?");
                pst.setString(1, comboroomnumber.getItemAt(comboroomnumber.getSelectedIndex()));
                rs=pst.executeQuery();
                if(rs.next())
                    txtprice.setText(rs.getString("price"));
            } catch (SQLException ex) {
                Logger.getLogger(CustomerCheckin.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    //Image set or adjustment coding in loading1 page.....
    public void scaleImage() {
        try {
            // Load the image from the file
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/ok.jpg"));

            // Scale the image to fit the label
            Image img = icon.getImage();
            Image imgScale = img.getScaledInstance(jLabel12.getWidth(), jLabel12.getHeight(), Image.SCALE_SMOOTH);
        
            // Set the scaled image as the icon of the JLabe6
           ImageIcon scaledIcon = new ImageIcon(imgScale);
            jLabel12.setIcon(scaledIcon);
        } catch (Exception ex) {
            // Handle exceptions, such as file not found or image loading error
          // ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtmobile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        combogender = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtnat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtadhar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboroomtype = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        combobed = new javax.swing.JComboBox<>();
        btncheckin = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        comboroomnumber = new javax.swing.JComboBox<>();
        txtprice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(948, 0, 52, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Customer Registration & Check IN.png"))); // NOI18N
        jLabel1.setText("Customer Checkin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 217, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 122, 302, 28));

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 168, 302, 32));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Mobile Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 218, 302, 29));
        getContentPane().add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 265, 302, 31));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 322, 302, 28));

        combogender.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        combogender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Transgender", " " }));
        getContentPane().add(combogender, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 368, 302, 32));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Nationality");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 426, 302, 27));
        getContentPane().add(txtnat, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 471, 302, 30));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Aadhar Card");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 527, 302, 27));
        getContentPane().add(txtadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 572, 302, 30));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("Check in Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 122, 299, 28));

        txtdate.setEditable(false);
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 168, 299, 32));

        jLabel8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("Bed Type");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 218, 299, 29));

        jLabel9.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 242, 242));
        jLabel9.setText("Room Type");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 322, 299, 28));

        comboroomtype.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        comboroomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "NON AC" }));
        comboroomtype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboroomtypeItemStateChanged(evt);
            }
        });
        getContentPane().add(comboroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 368, 299, 32));

        jLabel10.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(242, 242, 242));
        jLabel10.setText("Room Number");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 426, 299, 27));

        jLabel11.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(242, 242, 242));
        jLabel11.setText("Price");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 527, 299, 27));

        combobed.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        combobed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", " " }));
        combobed.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combobedItemStateChanged(evt);
            }
        });
        getContentPane().add(combobed, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 265, 299, 31));

        btncheckin.setBackground(new java.awt.Color(255, 51, 51));
        btncheckin.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btncheckin.setForeground(new java.awt.Color(242, 242, 242));
        btncheckin.setText("Check in Now");
        btncheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckinActionPerformed(evt);
            }
        });
        getContentPane().add(btncheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 662, 152, 44));

        btnclear.setBackground(new java.awt.Color(255, 51, 51));
        btnclear.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnclear.setForeground(new java.awt.Color(242, 242, 242));
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 662, 152, 44));

        comboroomnumber.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        getContentPane().add(comboroomnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 471, 299, 30));

        txtprice.setEditable(false);
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 572, 299, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/okko.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void btncheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckinActionPerformed
        // TODO add your handling code here:
        if(txtname.getText().equals("")){
            txtname.requestFocus();
            JOptionPane.showMessageDialog(this,"All field is required");
        }
        else if(txtmobile.getText().equals("")){
            txtmobile.requestFocus();
            JOptionPane.showMessageDialog(this,"All field is required");
        }
        else if(txtnat.getText().equals("")){
            txtnat.requestFocus();
            JOptionPane.showMessageDialog(this,"All field is required");
        }
        else if(txtadhar.getText().equals("")){
            txtadhar.requestFocus();
            JOptionPane.showMessageDialog(this,"All field is required");
        }
        else{
            
            try {
                pst=con.prepareStatement("insert into customer(name,mobile,gender,id,nationality,joindate,roomnumber,roomtype,bed,price,status)values(?,?,?,?,?,?,?,?,?,?,?)");
                pst.setString(1, txtname.getText());
                pst.setString(2, txtmobile.getText());
                pst.setString(3, combogender.getItemAt(combogender.getSelectedIndex()));
                pst.setString(4, txtadhar.getText());
                pst.setString(5, txtnat.getText());
                pst.setString(6, txtdate.getText());
                pst.setString(7, comboroomnumber.getItemAt(comboroomnumber.getSelectedIndex()));
                pst.setString(8, comboroomtype.getItemAt(comboroomtype.getSelectedIndex()));
                pst.setString(9, combobed.getItemAt(combobed.getSelectedIndex()));
                pst.setString(10, txtprice.getText());
                pst.setString(11, "NULL");
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Customer Checked in Successfully");
                txtname.setText("");
                txtmobile.setText("");
                txtnat.setText("");
                txtadhar.setText("");
                pst=con.prepareStatement("update room set status=? where roomnumber=?");
                pst.setString(1, "BOOKED");
                pst.setString(2, comboroomnumber.getItemAt(comboroomnumber.getSelectedIndex()));
                pst.executeUpdate();
                shyam();
            } catch (SQLException ex) {
                Logger.getLogger(CustomerCheckin.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
    }//GEN-LAST:event_btncheckinActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        txtname.setText("");
        txtmobile.setText("");
        txtnat.setText("");
        txtadhar.setText("");
        
    }//GEN-LAST:event_btnclearActionPerformed

    private void comboroomtypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboroomtypeItemStateChanged
        // TODO add your handling code here:
        shyam();
    }//GEN-LAST:event_comboroomtypeItemStateChanged

    private void combobedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combobedItemStateChanged
        // TODO add your handling code here:
        shyam();
    }//GEN-LAST:event_combobedItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncheckin;
    private javax.swing.JButton btnclear;
    private javax.swing.JComboBox<String> combobed;
    private javax.swing.JComboBox<String> combogender;
    private javax.swing.JComboBox<String> comboroomnumber;
    private javax.swing.JComboBox<String> comboroomtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtadhar;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnat;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
